name: Build RC version
on:
  push:
    branches:
      - develop

jobs:
  build_image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Read release.json
      uses: notiz-dev/github-action-json-property@release
      id: version_info
      with:
        path: 'release.json'
        prop_path: 'version'

    - name: Show version number
      run: echo "Version is ${{ steps.version_info.outputs.prop }}"

    - name: Login to registry.osmollo.ovh
      uses: docker/login-action@v3
      with:
        registry: registry.osmollo.ovh
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}

    - name: Build, tag, and push image to registry.osmollo.ovh
      env:
        docker_user: osmollo
        docker_image: my_alpine
        docker_version: ${{ steps.version_info.outputs.prop }}
      run: |
        docker build -t registry.osmollo.ovh/$docker_user/$docker_image:$docker_version .
        docker push registry.osmollo.ovh/$docker_user/$docker_image:$docker_version
        docker tag registry.osmollo.ovh/$docker_user/$docker_image:$docker_version registry.osmollo.ovh/$docker_user/$docker_image:latest
        docker push registry.osmollo.ovh/$docker_user/$docker_image:latest
